apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-hello-world
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: nginx-hello-world
    spec:
      containers:
      - name: nginx-pod
        image: arungupta/nginx-hello-world
        ports: 
        - containerPort: 80
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-hello-world-service
spec:
  selector:
    app: nginx-hello-world
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
